### ISSUE TITLE
Updates RFC 1035

### ISSUE THREAD

**Issue by pusateri** [raybellis/draft-bellis-dnsop-session-signal#10]
Decide if this draft should claim to update RFC 1035

**Comment by StuartCheshire** [comment]
Agreed during 2nd August conference call: Yes, we should state that this document Updates RFC 1035. This document defines the Keepalive TLV and once a session is set up allows either end to send it. Similarly the Push document defines the Push TLVs and specifies the rules for those. Neither document modifies the rules for existing opcodes.
