### ISSUE TITLE
Can response be optional?

### ISSUE THREAD

**Issue by pusateri** [raybellis/draft-bellis-dnsop-session-signal#11]
draft-sctl-dnssd-mdns-relay wants to use session signaling and not require a response to the mDNS TLV.

**Comment by Abhayakara** [comment]
We should define a modifier TLV that says "no response is required".   We may want similar TLVs for other behaviors.

**Comment by Abhayakara** [comment]
Change of plan: Stuart points out that using a TLV is easy to get wrong without breaking interop between client and server.   So we will use a bit instead.

**Comment by StuartCheshire** [comment]
Agreed during 8th August conference call: The problem with the modifier TLV is that some clients might forget to put it in. We will partition the DSOP type values into two halves, with a bit to signify which type values require a response and which do not.
