### ISSUE TITLE
Rename draft

### ISSUE THREAD

**Issue by johndickinson** [raybellis/draft-bellis-dnsop-session-signal#12]
Proposal:  Bi-directional DNS Session Operations

Rationale: Biggest change from regular DNS is that operations can be initiated by either end. Also the TLVs are not limited to "signalling" - the biggest use case is DNS Push so the term operation is more appropriate. 

Ensure session terminology is correct

**Comment by saradickinson** [comment]
New proposal: DNS Statefull Operations

**Comment by raybellis** [comment]
file name needs to be reverted back to the original even though the draft title has changed
