### ISSUE TITLE
Correct text describing session establishment

### ISSUE THREAD

**Issue by johndickinson** [raybellis/draft-bellis-dnsop-session-signal#13]
"A "session" is established over a
   connection when either side of the connection sends the first session
   signaling operation TLV and it is acknowledged by the other side.
   While this specification defines and initial set of two operations,
   additional operations may be defined in additional specifications."

This is incorrect since only a client can send the TLV that establishes a session. 

Also make this a MUST NOT:
"A server SHOULD NOT initiate Session Signaling messages until a
   client-initiated Session Signaling message is received first..."

**Comment by raybellis** [comment]
following call on August 2nd determined that under some circumstances a server MAY unilaterally initiation stateful operations.
