### ISSUE TITLE
Does restriction on name compression apply to encapsulated data?

### ISSUE THREAD

**Issue by johndickinson** [raybellis/draft-bellis-dnsop-session-signal#17]
For example encapsulated mDNS messages?

**Comment by StuartCheshire** [comment]
Agreed during 2nd August conference call: Need clarifying text that the no-compression rule does not apply to opaque encapsulated data.

**Comment by pusateri** [comment]
Value in the TLV is a blob and should not reference any other TLVs.
Name compression inside the value portion may be defined by the TLV.
The offset of 0 is considered the beginning of the value of that TLV.

**Comment by johndickinson** [comment]
closed as done in 4c30116783c8a6ed2b5106ab5b329ec04f558ff7
