### ISSUE TITLE
Clarify client behaviour on receiving a Keepalive TLV

### ISSUE THREAD

**Issue by johndickinson** [raybellis/draft-bellis-dnsop-session-signal#18]
I’m still a bit confused about the use of the Keepalive message. The text explicitly says that this message doesn’t update the idle timeout but that it should be used to request a longer idle timeout. So... what should a client do when it receives a Keepalive response
- nothing if the session timer values have not changed?
- if the session timer values have changed should it
 - reset the timer and use the value just received?
 - wait and only use the new value on the next timer reset?
 - only do this with the idle timer because the keepalive timer was reset on sending the message

**Comment by StuartCheshire** [comment]
Agreed during 2nd August conference call: Sara will elaborate cases that are currently ambiguous.

**Comment by StuartCheshire** [comment]
I have [added text](https://github.com/raybellis/draft-bellis-dnsop-session-signal/commit/ba223ceaa6d599e6de971044b99acbefaba9215a) which hopefully addresses these questions.

**Comment by saradickinson** [comment]
Fixed in the -04 update
