### ISSUE TITLE
RCODES seem to be redefined in the Push draft

### ISSUE THREAD

**Issue by johndickinson** [raybellis/draft-bellis-dnsop-session-signal#19]
It would be better to have one set of RCODES defined in this draft that is re-used by all the TLVs. Currently the PUSH draft specifies which RCODES are supported based on the operational TLV and defines additional RCODES not in this draft.

**Comment by pusateri** [comment]
We can include the ones we know about now but when future TLVs are added, they should be able to define additional RCODES. So we can add something to the draft saying so.

**Comment by StuartCheshire** [comment]
Agreed during 2nd August conference call: Document should explicitly state that RCODEs 12-15 are currently unused and reserved for future assignment.

**Comment by raybellis** [comment]
resolved by https://github.com/raybellis/draft-bellis-dnsop-session-signal/commit/c51ec2828fbfa15cdbfb786d040c78245ba9f6dc
