### ISSUE TITLE
Is starting a DSO session restricted to messages that require a response?

### ISSUE THREAD

**Issue by saradickinson** [raybellis/draft-bellis-dnsop-session-signal#24]
Currently section 4.1 says:

   A "session" is established over a connection when
   either side of the connection sends the first DSO TLV and it is
   acknowledged by the other side.

**Comment by pusateri** [comment]
I think this must be true. We need both sides to indicate they support DSO.

**Comment by saradickinson** [comment]
Agreed. I'll make sure the draft clarifies this.

**Comment by saradickinson** [comment]
TO FIX in next version: 
Section 4.3 of -04 still says "Every DSO request message (QR=0) MUST elicit a response (QR=1)"

**Comment by pusateri** [comment]
Need a NO ERROR response.

**Comment by StuartCheshire** [comment]
Fixed in commit 19ae5b1fef8aab02bd062e7b0f19bb45d5561bd3
