### ISSUE TITLE
Can the operational TLV be anywhere in the TLV list to simplify parsers?

### ISSUE THREAD

**Issue by pusateri** [raybellis/draft-bellis-dnsop-session-signal#27]
Ted would like to lift the restriction that the first TLV be the operational TLV. The implications are:
1. a TLV type is fixed as modifier or operational OR we add a bit to specify which TLV is operational.
2. if you don't understand the TLV type, you won't know if it's an operational TLV if you don't have a bit.
3. since you can ignore modifier TLVs you don't understand but not operational TLVs you don't understand, whether you process the known modifier TLVs depends on if you understand the operational TLV.

**Comment by Abhayakara** [comment]
We have decided to use a no-op TLV and require that the operation be the first.
