### ISSUE TITLE
DNS Proxy

### ISSUE THREAD

**Issue by pusateri** [raybellis/draft-bellis-dnsop-session-signal#8]
Describe DNS Proxy message handling

**Comment by raybellis** [comment]
Query on how dnsdist currently handles receiving the new opcode.  Does it return `NOTIMP` or does it forward the query upstream?

**Comment by raybellis** [comment]
pDNS authors say that dnsdist would forward the opcode blindly unless there was a special rule, and also close any inbound connection that has QDCOUNT == 0

**Comment by raybellis** [comment]
addressed by a2b3739d984c0ae2c18b3040dee0f6411e2f3486

**Comment by saradickinson** [comment]
Addressed in -04 update
