### ISSUE TITLE
Resolve ordering requirements

### ISSUE THREAD

**Issue by pusateri** [raybellis/draft-bellis-dnsop-session-signal#9]
It is possible to move the ordering requirement from the main spec to the TLVs that require it.

**Comment by johndickinson** [comment]
Retaining ordering seems useful, however we probably need to clarify the ordering between session signalling messages and regular DNS e.g. if a client sends a keepalive then it shouldn't send any regular DNS until it has the response and knows if a session is established or modified. The DNS messages can be treated out of order as described in RFC7766 but we should be careful with the relative order of TLVs that may modify the session state and regular DNS messages.

**Comment by saradickinson** [comment]
Also need to specify order of transmission (not receipt) I think? This will make it easier to apply to QUIC if that day comes.

**Comment by pusateri** [comment]
Yes, to capture the latest discussions we had at IETF, I think we want to specify that order of session signaling messages must be preserved from the sender to the receiver. If we tried to do this ourselves, we would be reinventing the transport protocol.

**Comment by pusateri** [comment]
Section 8.1 needs changed. Currently it says "The server MUST act on messages in the order they are
   received, but responses to those messages MAY be sent out of order,
   if appropriate." This should say something like the receiving end should act on the messages in the order they were transmitted. It is up to the transport layer to ensure the receiving side is aware of the order they were transmitted.

**Comment by saradickinson** [comment]
Addressed in the -04 update
